### ISSUE TITLE
About window

### ISSUE THREAD

**Issue by KSib** [paolosalvatori/ServiceBusExplorer#125]
The about window doesn't seem to have the version number in it, but it does seem to cause very high CPU usage ;)

**Comment by paolosalvatori** [comment]
Mmm... the tool tries to retrieve the version from GitHub via HTTP. Are you sure you are connected to the internet?

**Comment by KSib** [comment]
Always :) Maybe this was a fixed bug? I'm on 4.0.68

**Comment by KSib** [comment]
So I updated by compiling what was in the zip file.
The version number on the title has the correct version. The version number in the window itself says 1.0.0

![image](https://user-images.githubusercontent.com/1589238/27392752-140bc51e-566d-11e7-9898-a7b338426866.png)

**Comment by paolosalvatori** [comment]
Here is the deal. If you download the latest release from https://github.com/paolosalvatori/ServiceBusExplorer/releases, the exe automatically contains the latest version. Since it's not possible to automatically change the source code whenever a new release is created to reflect the new version, or generated the right version number when you build the source code locally, the code automatically retrieves the version of the latest release from GitHub at runtime. I don't think it's really important. :)
