### ISSUE TITLE
Introduce .editorconfig to provide code standards guidance

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#160]
As suggested by @lenardg during work on PR #159.

**Comment by lenardg** [comment]
@SeanFeldman I might have mixed things up a little: .editorconfig only affects tabs/spaces and newline settings, and cannot directly affect how braces are formatted for C#. Sorry about that! 

That said, I still think it would be good to have an .editorconfig, because I usually code with tabs but your project uses spaces. An .editorconfig means VS2017 and other .editorconfig based editors will not try to tabify the project when someone with different settings edits the files.

**Comment by paolosalvatori** [comment]
Hi @lenardg could you please clarify your suggestion? Thanks!
P.S Service Bus Explorer is my project :) Sean is a super valuable collaborator :)

**Comment by lenardg** [comment]
Sure!

.editorconfig is a file that instructs the editor (in this case Visual Studio) to use certain settings relating to indentation settings in C# and .config files. Your project uses 4 spaces to indent C# source code and 2 spaces to indent .config files. This .editorconfig is set up to instruct VS2017 to use that.

So even if my Visual Studio is set up to use tabs for indentation and that indents are 8 characters deep, when I open a project with this .editorconfig, VS will still use 4 spaces. 

I actually use tabs for indentation (it is what we use in our company), so I had to take special care when contributing to ServiceBusExplorer to not commit anything with tabs in it, but use spaces like your project does. When the .editorconfig is added, VS takes care of this, and will still use spaces, regardless of the user settings.

Read more about it here: http://editorconfig.org/

(VS2017 has built in support, previous VS versions require a plugin to be installed in order for this to work).

Hope this clarifies what this is! :)

**Comment by SeanFeldman** [comment]
@paolosalvatori here's [VS specific doco](https://almvm.azurewebsites.net/labs/tfs/editorconfig/).

**Comment by SeanFeldman** [comment]
More inclusive (and official) documentation on VS2017 options that can be used: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference
