### ISSUE TITLE
Messages should be sent in batch for Repair and Submit

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#208]
PR #206 has changed the original code that was sending messages in batches.
To address perf and UX, batching needs to be re-implemented.

**Comment by ErikMogensen** [comment]
I can work on implementing batchign, unless someone else is already doing it.

**Comment by SeanFeldman** [comment]
I don't have capacity ATM, but can point at what I've done in the past.
Just breaking messages into batches is not going to work. The size reported by `BrokeredMessage` is always smaller than the actual size over the wire. Instead, what I've done is breaking a batch into multiple ones (chunking) using some estimated size. [The post](https://weblogs.asp.net/sfeldman/asb-batching-brokered-messages) is two years old, but customers didn't have issues with this approach so far 🙂

**Comment by ErikMogensen** [comment]
This was more complicated than I initially thought. My plan of approach was to extend https://github.com/paolosalvatori/ServiceBusExtensions using the solution in Seans excellent post https://weblogs.asp.net/sfeldman/asb-batching-brokered-messages, but support for non-string custom properties needs to be added. We do seem to run into edge cases, like the size issue with message size in issue #195, so this cannot be omitted. I also looked at https://mikhail.io/2017/07/sending-large-batches-to-azure-service-bus/. As both solutions might have issues with other message formats - there are many: https://abhishekrlal.com/2012/03/30/formatting-the-content-for-service-bus-messages/ this complicates things. Then there is the error handling in case a batch fails to be delivered. In short, besides a tricky implementation part adding this feature would require extensive testing.

The issue of batching is solved in the new Service Bus client and therefore I feel it is not worth spending more time on this feature. I suggest this issue is closed.

**Comment by SeanFeldman** [comment]
The challenge with `Dictionary<string,object>` based headers is that we'll not be able to know the size until object graph is serialized. That's the reason I didn't bother with anything other than `Dictionary<string, string>` (what my customers use).
