### ISSUE TITLE
Survey questions

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#211]
- Is the tool used as a dev tool or IT/Ops
  - If both, what's the percentage (50/50, 40/60)
- Are you using ASB with Windows / Linux / both?
- Is lack of support for cross platform prevents you from using SBE?

**Comment by tomkerkhove** [comment]
- Are there service that you want to use, but not supported yet?
- Would you like to contribute?
- What feature would you like to be added?
- How are you installing the tool or are you just downloading it?

**Comment by paolosalvatori** [comment]
- Are you using Service Bus Explorer to:
   > analyze metrics?
  > manage and test notification hubs?
  > receive messages from IoT Hub?
  > receive or send messages to a Stream Analytics job?
  > receive or send messages to Azure Functions?
  > receive or send messages to Microsoft Dynamics CRM?
 - Would you like to use Service Bus to:
   >create \ delete \ update Event Grid custom topics and subscriptions?

**Comment by ErikMogensen** [comment]
> Currently there's only one way to install it - chocolatey. Should the question be more specific and ask to choose the way application is deployed with three options?
> 
> 1.  Pull down the code and compile
> 2.  Download the ZIP from GitHub release page
> 3.  Use chocolatey

I have packaged Service Bus Explorer into an MSI using the VS Installer Projects Extension to handle customizations and make it easier to distribute internally. Therefore I suggest a forth option:
4. Use a custom packaging, like MSI

- Some of the services that Service Bus Explorer handle do not have Service Bus in their names anymore. There might also be more services added to Service Bus Explorer that also lack the name Service Bus. However, it is always some pain involved when changing a name. Do you think it is a good idea to change the name of the tool to something like Azure Message Explorer?

**Comment by paolosalvatori** [comment]
@ErikMogensen I'd prefer not to rename the tool. :) In addition, Azure Message Explorer could make people think that it covers also Azure Queues that instead are not currently supported by the tool. I'm good with extending the tool to create an MSI.

**Comment by regevbr** [comment]
I had to create a windows vm to use that tool as I'm working on Ubunutu now.
Creating a linux dist will be awesome!!!

**Comment by paolosalvatori** [comment]
Hi @regevbr I think that the Service Bus team is working to extend the ability to manage, control and test the entities of a Service Bus Messaging namespace. Maybe @djrosanova and @clemensv can provide more information at this regard. This would make creating a cross-platform version of SBE unnecessary. I do understand your request, trust me, but I'm not a member of the Service Bus team and I'm maintaining the tool on a best effort basis with the help of the community and in particular @SeanFeldman, @ErikMogensen and @tomkerkhove

**Comment by regevbr** [comment]
Hi @paolosalvatori thanks for the answer. Sadly management tools provided by Azure (or AWS for that matter) are (if they even exist) really lean and not usefull. They rely on you to use their api to manage your services. Even if they extend the tools a little bit, I'm sure it will not give the great benefits this tool brings and certainly will not make a cross platform version unnecessary... What do you think?

**Comment by paolosalvatori** [comment]
I totally agree with you, it would be great to have a multi-platform tool for Service Bus, but even if I work at Microsoft, a complete re-write of the tool would be a huge effort and is not in my commitments, sorry about that :(

**Comment by SeanFeldman** [comment]
I will mention Serverless360 as an option. It's not free, but it's xplat.
In regards to re-write, it's not a small undertaking, just like Paulo has mentioned.

**Comment by sjwaight** [comment]
I've had a few folks chime in recently asking about x-plat for SBE. Appreciate it's a big ask, but the lean pickings in the Portal don't provide good enough support to replace SBE on non-Windows platforms. Yes, there are commercial tools (which people should be happy to pay for if they are using the tool for prod support), but the fact that SBE is already free (and prevailing attitudes) does mean people are expecting low/no-cost tooling. Using Data Studio as a foundation would make the most sense over Storage Explorer...

**Comment by ErikMogensen** [comment]
@sjwaight , there are some good news! At the Integrate conference two weeks ago the PM for Service Bus, Ashish Chhabria, showed a new feature in the Azure Portal called Data Explorer. It allows you to look at the content of messages on Service Bus queues. I think Ashish said it would be available next month.

Data Studio, do you mean https://datastudio.google.com/overview? Looking at that site it seems that it is a reporting tool and it would be great to have a connector to Service Bus for it. That is something to let the Service Bus team know and quite different from SBE.

The SBE code base is huge. According to VS 2019 v16.1.3 it currently consists of 100 000 lines of C# (46 000 according to VS 2017 v15.9.13) and roughly two thirds of the code is for handling the GUI. The GUI is built on Windows Forms. It recently become possible to run Windows Forms in .Net Core but only on Windows. The current x-plat alternatives I am aware of are Mono, Electron and Asp .Net Core. I don't think there is a supported Service Bus client for Mono. If swithcing to Electron we would need to rewrite everything as I understand it. Asp .Net Core does not have as rich capabilities for GUI as Windows Forms and would create quite a different user experience since it would require a web site and a browser.

We are looking at making SBE x-plat but it is difficult. Ideas are very welcome. For that and other reasons we want to migrate to the new Service Bus client which is based on .Net Standard and thus x-plat. That is a big step which will probably take a year from now, depending upon how much the community contributes to this task since there are no dedicated developers. But even after having changed to the .Net Standard based Service Bus client, SBE won't be x-plat due to its dependency on Windows Forms. I  hope Microsoft will create x-plat support for Windows Forms in the next major .Net version. If that happened going x-plat would not be so hard.

**Comment by paolosalvatori** [comment]
Agreed, if the .NET Core team provide x-plat support for Windows Forms, we could migrate SBE to .NET Core and make it available for other platforms.
