### ISSUE TITLE
An exception including its stack trace is shown in the Log window when a namespace lacking Notification Hubs is opened

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#213]
An exception including its stack trace is shown in the Log window when a namespace lacking Notification Hubs is opened. For instance:
```
<20:34:32> Failed to retrieve Notification Hub entities. Exception: System.ArgumentException: 
The remote server returned an error: (400) Bad Request. Bad Request. TrackingId:, SystemTracker:NoSystemTracker, 
Timestamp:5/7/2018 6:34:29 PM ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.

              at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

```
This is probably caused by the PR #207 that changed the exception handling. I suggest adding special handling for exceptions thrown when checking for Notification Hubs and suppressing the exception thrown for this scenario. 

Or remove the support for Notification hubs.

**Comment by tomkerkhove** [comment]
I can confirm this bug, however I think we should rename this one or create another one since the problem is bigger than this because if you use a valid Notification Hubs connectionstring, everthing is fine:
![image](https://user-images.githubusercontent.com/4345663/39833471-bd21f1b2-538f-11e8-90ac-f2cfc137c054.png)

But exceptions start popping up for the other entity types.

Problem is that we support multiple types of services which each have their own connection string:
- **Service Bus Namespace**: Queues and optionally topics, based on service tier
- **Notification Hubs Namespace**: Notification Hubs
- **Event Hubs Namespace**: Event Hubs

Based on the type of connection strings we should only show the icons of the services that are supported and hide the other ones. However, this also means that we will need to swallow this particular type of exception.

**Comment by tomkerkhove** [comment]
Personally I would try to connect to all entities and determine the outcome:
- If nothing was found, throw
- If I have event grids, hide the rest and don't throw
- If I have notification hubs, hide the rest and don't throw
- If I have queue, hide the rest and don't throw. If it couldn't get topics and tier is above basic, throw

Removing support for Notification Hubs would be a bit of a pity given the service is not deprecated yet and existing users no longer couldu se it

**Comment by paolosalvatori** [comment]
Hi @tomkerkhove I already implemented this behavior:

"Based on the type of connection strings we should only show the icons of the services that are supported and hide the other ones. However, this also means that we will need to swallow this particular type of exception."

The change that was recently introduced, broke my implementation of this behavior. We need to re-establish this functionality. I asked several times to the product group to provide the ability to indicate right in the connection string the kind of Service Bus namespace (messaging, event hub, notification hub), but in vain. You can retrieve the kind of namespace resource using the management REST API, but in order to invoke the REST API you need to authenticate against an AD tenant using user credentials and a library like ADAL to create a SAS token. So the technique I had to use is the following:
for each entity type, the code (AFAIR the name of the method is MainForm.GetEntities) tries to retrieve items from the namespace. If the call succeeds, the root node (e.g. Event Hubs) is created in the TreeView and one node for each entity is created below it. It the call  fails or times out, the root node is simply not created.
Another method to avoid exceptions, it's to explicitly indicate the entities you want to retrieve in the Connect form. 

**Please, do not remove the support for notification hubs.**
