### ISSUE TITLE
Partitioning is not available on Premium

### ISSUE THREAD

**Issue by SeanFeldman** [paolosalvatori/ServiceBusExplorer#214]
Unlike [in the past](#120), ASB [Premium tier is no longer using Partitioning](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning#premium) and it should be disabled.

With no option to determine type of namespace (until namespace manager package is available or other alternative is impleneted), there's no way to determine if Partitioning option should or should not be available.

**Comment by paolosalvatori** [comment]
True, but apparently there's nothing we can do. Understanding the sku of a namespace (standard or premium) pose the same issue of determining the kind of namespace (Service Bus, Event Hubs) :(

**Comment by SeanFeldman** [comment]
> there's nothing we can do

There always is. Just not optimal. We can wait for the new [namespace management package](https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-338874419). That one should have this bit.

**Comment by ErikMogensen** [comment]
Using the REST API it is should be possible to determine whether it is running Premium or not; https://docs.microsoft.com/en-us/rest/api/servicebus/namespaces/get.

**Comment by paolosalvatori** [comment]
@ErikMogensen true, but it requires to use an AD user to get an authorization token, the connection string is not enough. :(

**Comment by ErikMogensen** [comment]
I thought it was too easy and obvious :)

Another idea, which is not pretty but if it is important to determine SKU could be worth considering:

Since Premium does not report/support partitioned queues anymore check if anyone of the existing queues is partitioned, then we know.

If there aren't any partitioned queues, check if any queue is larger than 5 GB, then it is Premium.

Finally if those checks didn't reveal SKU, politely ask the user for permission to create a queue for determining SKU. First try to create a partitioned queue and if that didn't work, try to create a 20 GB queue. Call the queue something like z_ServiceBus_Explorer_<SKU>_May_be_deleted. That way ServiceBus Explorer would know the SKU next time.

Also show SKU on the root node, where Unknown would be a possible value. In that case functionality may be limited.

**Comment by paolosalvatori** [comment]
Thanks @ErikMogensen in case the test is positive, yes, you know the namespace is using the Premium pricing tier, but if the test is negative, this doesn't necessarily mean that the namespace is Standard :) I appreciate your workaround :) We may also extend the connect form and ask the user to specify if the namespace is standard or premium, without making any internal test.

**Comment by ErikMogensen** [comment]
I edited my last response in this thread to make it clearer or at least less unclear :) I do not see how the tests above would fail to determine SKU. It will fail on the Basic SKU, but I believe those do not exist anymore.

Since many users don't know whether they are running Premium or Standard I think it is better in most cases to get that information technically.

**Comment by SeanFeldman** [comment]
> We may also extend the connect form and ask the user to specify if the namespace is standard or premium, without making any internal test.

Yep. That's what all tools are doing while defaulting to standard.

While proposed workarounds are creative, let's not get carried away 😃 
Also, we need to move on. The new client is going to add basic management operations with support for namespace SKU reporting. 

My vote is to move off the old client. Or at least leverage the new one for things such as determining SKU.

**Comment by paolosalvatori** [comment]
Agreed, let's progressively migrate to the new library starting from SKU discovery.

**Comment by ErikMogensen** [comment]
Since we got this functionality in #504 this can be easily be implemented..
