### ISSUE TITLE
Put the connection strings in a file in the users personal folder

### ISSUE THREAD

**Issue by ErikMogensen** [paolosalvatori/ServiceBusExplorer#232]
That way the strings would be a little bit more protected and when downloading a new version of SBE you’d keep your connection strings. 

Add an option to use the connection strings in the application config file for backwards compatibility, even though it is not recommended. 

In the future encryption of the strings may be added using DPAPI and that may not work when using the Roaming profile. Therefore use the local non-roaming profile for this.

**Comment by tomkerkhove** [comment]
Maybe it would be align with other tools and go for storing it in `C:\Users\<user>\.servicebusexplorer`?

One might argue that the tool should integrate with Azure Key Vault as well, although this should be a dedicated issue I think.

**Comment by SeanFeldman** [comment]
> Maybe it would be align with other tools and go for storing it in C:\Users\<user>\.servicebusexplorer

Will not pretend I'm an expert, but rather than using `%UserProfile%` settings should be stored in `AppFolder`. This tool is not cross-platform to target user profile root directory with a dot-notation.

I'm using more than a single machine, and consider roaming settings `%AppData%` more useful as settings saved there are transferable and survive machine repaving.

FYI: `%AppData%` translates into `%UserProfile\AppData\Roaming`.

> One might argue that the tool should integrate with Azure Key Vault as well, although this should be a dedicated issue I think.

Gonna call YAGNI on that.

> Add an option to use the connection strings in the application config file for backwards compatibility, even though it is not recommended.
>
> In the future encryption of the strings may be added using DPAPI and that may not work when using the Roaming profile. Therefore use the local non-roaming profile for this.

Always a fan of "start simple and see what people are asking for".

**Comment by paolosalvatori** [comment]
Agreed with everything. Let's make sure to guarantee backward compatibility :)

**Comment by SeanFeldman** [comment]
And [here's the reason](https://github.com/paolosalvatori/ServiceBusExplorer/pull/236/commits/e5744a5cad8f75ed53380f5ed7c7f06bed4750c1) why I still think keeping connection strings in app.config is a **bad** idea.
![image](https://user-images.githubusercontent.com/1309622/42704683-0940bf48-868e-11e8-84ec-40900fb26ac1.png)

PS: @paolosalvatori you might want to reset all of your SAS tokens...
