### ISSUE TITLE
add ability to auto resubmit all dead letter messages

### ISSUE THREAD

**Issue by regevbr** [paolosalvatori/ServiceBusExplorer#301]
A common scenario (at least for me) it when a bunch of message gets to the DLQ and I want to resubmit them back to the queue after I know they won't fail again.
Currently I need to retrieve all messages (while deleting them) and then resubmit to the queue.
It will be awesome if there will be a button to handle all of that logic.

**Comment by ahofman** [comment]
I do this now with auto-forwarding. 

Given a queue "A" with dead lettered messages. I create a new queue called "B". Then configure queue "A" to forward all dead lettered messages to "B" and then update. All the dead lettered messages should then be in "B" and the DLQ for "A" should be empty. Then configure "B" to forward all messages to "A" and update. All messages will then be back in "A" and be available for processing.

**Comment by regevbr** [comment]
@ahofman I thought about that solution a while back but it doesn't do what I need - what you actually do can be done by setting the number of retries of a message to infinite and ignore the existance of the DLQ.
I do want my messages to go the DLQ under certain conditions, and WHEN I want to resubmit them, I will be able to do it with ease.

@ahofman do you agree or am I missing something?

**Comment by ahofman** [comment]
I don't think we're quite on the same page - I am not suggesting ignoring the DLQ or anything like that. I'll try again but with more detail.

Let's say you have a queue called "A". This queue is configured with Max Delivery Count of 10. There were 100,000  messages in this queue that have been received 10 times, and their delivery count has exceeded the Max Delivery Count, and all the messages have been dead-lettered. So what we have in this scenario is a queue called "A" with 0 active messages and 100,000 messages in the dead letter queue for "A". The objective is to resubmit all 100,000 messages from the DLQ in "A" such that they are active again in "A", with their delivery counts reset, so that they can be processed again. 

To achieve this, create a new queue called "B". Then configure queue "A" to forward all dead-lettered messages to "B", like so (don't forget to click the Update button): 
![image](https://user-images.githubusercontent.com/1689712/52551242-b8c88380-2e2f-11e9-9e5c-9a86e91e99c1.png)

After refreshing the queues, you will see 100,000 active messages in "B" and 0 dead lettered messages in A. The active messages in "B" will have a Delivery Count of 1.

Now configure queue "B" to auto-forward all messages to "A", like so (don't forget Update): 
![image](https://user-images.githubusercontent.com/1689712/52551305-004f0f80-2e30-11e9-9d60-7e2d348d1dcd.png) 

We'll now see 100,000 active messages in "A" with a delivery count of 1, ready to be processed - mission accomplished :) (unless of course I've missed something!) 

Note in this scenario we've set up a loop of automatic retries of dead lettered messages in "A" - hence we should turn off the auto-forwarding once we've completed the retry operation.

**Comment by regevbr** [comment]
Yes that make more sense when you do it ad-hoc and then disable it.
The thing is that it takes time and if I have 10 queues with stuck dead messages? It will take a long time to acomplish.
The manual process I do currently takes a bit less time but if I had to deal with 100k dead messages I will defiantly use your method.
I still think it will make much more sense to have a single button to perfrom the operation in the UI - it will take 5 seconds to handle 10s of queues!

**Comment by paolosalvatori** [comment]
Hi @regevbr Service Bus Explorer is an open-source tool and is supported by the community on a best-effort basis. Unfortunately, in the last couple of years I've been quite busy and I've a limited time to dedicate to the tool. I think that your idea is good, but at the same time your issue is not so common. In other words, it would be great if you could implement the feature you suggest and submit a PR. Otherwise, I can look into it, but not now, because I don't have time in this period, sorry about that :(

**Comment by regevbr** [comment]
I completely understand! Last I touched c# was a few years back and I'm a node.js guy now but if i will find the time I will try to give it a shot

**Comment by paolosalvatori** [comment]
thanks @regevbr ;)
