### ISSUE TITLE
Allow user to configure third number shown next to service bus queue name

### ISSUE THREAD

**Issue by MikeWilliams-UK** [paolosalvatori/ServiceBusExplorer#313]
While fixing an unrelated bug I finally found out what the third number shown is. It's the "TransferDeadLetterMessageCount"

As we don't use this I have compiled a version for our internal use, which shows the "ScheduledMessageCount" which we use instead.

A usefull enhancement might be to allow the end user to be able to configure which counts are shown next to the queue in the tree view.

![image](https://user-images.githubusercontent.com/13162784/54025451-7c6c1700-4192-11e9-98be-2b3efce12461.png)

**Comment by SeanFeldman** [comment]
Originally, the tool showed just two numbers: active and dead-lettered message counts. And that's because every queue is technically two queue: the actual queue and DLQ sub-queue.

Transfer dead-lettered messages where added as a result of the discovery of a very poorly documented fact that T-DLQ is yet another sub-queue. What's worse is that when that sub-queue contains messages, errors caused those messages to begin with would never be logged or surfaced to the users.

In terms of usability, I can see that someone who's not concerned about T-DLQ-ed messages would rather see Scheduled messages. Or perhaps Deferred messages? After all, deferred messages cannot be received and have to be proactively fetched to be processed. So should the configuration allow to chose between these 3 options? Or maybe we need to revisit the UI (which BTW is already showing that information).

![image](https://user-images.githubusercontent.com/1309622/54059607-f7472900-41b6-11e9-8cf2-4a623c452c42.png)

Let's discuss 🙂

**Comment by MikeWilliams-UK** [comment]
I 100% agree with you that the UI shows the full info for the "selected" queue. However in our case we need to monitor several queues, so we select the queues node and press F5 and get an overview we can then click on the queue we want detailed info on.

The option I was think about was to keep the first two counts as fixed, then allow the user to chose which other count was displayed as the third number.

**Comment by paolosalvatori** [comment]
Hi @MikeWilliams-UK you can eventually submit a PR to eventually add a dropdownlist to the Options form that allows to select what the third number shows: TransferDeadLetterMessageCount, ScheduledMessageCount, TransferMessageCount or TransferDLMessageCount. Meanwhile, I close this issue.
