### ISSUE TITLE
Temporary freeze when Peeking more than a few messages

### ISSUE THREAD

**Issue by apjanke** [paolosalvatori/ServiceBusExplorer#316]
I'm a new SBE user; sorry if this is user error.

I have a Service Bus Queue with a single small message in it. If I try to retrieve 500 or 1000 messages from this queue in Peek mode, the SBE UI freezes for quite a while: over a minute in the case of 1000 messages.

It's frozen pretty hard, too: if I raise another window on top of the SBE window and click back on to SBE, it doesn't come back on top. And there is no indication of activity: the mouse cursor over SBE isn't turned into an hourglass, there's no progress meter, etc.

Could the GUI be made more responsive while SBE is working to peek messages? Maybe with a progress dialog/indicator with a Cancel option?

And maybe something could be done about how long it's frozen? This is a queue with only one message in it. Maybe it's not stopping its work when it hits the end of the queue? Or maybe something else is going on?

Also, why isn't the "All" option available in Peek mode when retrieving messages?

**Comment by ErikMogensen** [comment]
Good questions.

> Could the GUI be made more responsive while SBE is working to peek messages? Maybe with a progress dialog/indicator with a Cancel option?

The calls to Service Bus are synchronous and this issue might be resolved by making them asynchronous. Care needs to be taken though to handle other things the user might do during loading. Adding a progress bar would be great, but I think it is difficult to implement properly. 
 
> And maybe something could be done about how long it's frozen? This is a queue with only one message in it. Maybe it's not stopping its work when it hits the end of the queue? Or maybe something else is going on?

Right now it is a single-threaded operation, by making the peeking multi-threaded that would make it go faster. The messages would be loaded either in a List or directly in the UI. When done a sort on sequencenumber would have to be done to get the messages in the right order.

> Also, why isn't the "All" option available in Peek mode when retrieving messages?
I guess that it is because of the reason you mentioned above; that it does not know when to stop and have to timeout. To solve this a check for message count would have to be done at the start and then quit when that is reached, perhaps trying an extra time to check if there are any new messages. 

Of course if a lot of messages are removed while peeking the queue the operation will take a long time anyway.

@apjanke , it was some ago you created a PR... ;)

**Comment by paolosalvatori** [comment]
Hi @apjanke I think that @ErikMogensen answered your question. The solution is to peek a relatively small number of messages or refactor the code to use await/async methods. Take into account that await/async methods were not available when the UI was originally created years ago. Feel free to submit a PR :) Meanwhile, I'm closing the issue.
