### ISSUE TITLE
Re-submitting message with Guid property

### ISSUE THREAD

**Issue by jonsb** [paolosalvatori/ServiceBusExplorer#34]
When re-submitting a message that has a Guid property, the property is not included in the re-submitted message, apparently because the "value as string" cast below will return null (value is of type Guid, not string):

ConversionHelper.cs

public static object MapStringTypeToCLRType(string type, object value)
...
case "Guid":
                    return new Guid(value as string);
...

For me, changing "value as string" to "value.ToString()" seems to solve the problem, but I don't know the complete implications of this fix, and I don't know why "value as string" was written in the first place.

**Comment by SeanFeldman** [comment]
A few thoughts:

1. Could have a unit test for this kind of functionality to seal what the expected behaviour should be (issue #36 is raised)
1. [`MapEDMTypeToCLRType`](https://github.com/paolosalvatori/ServiceBusExplorer/blob/7f87a15bbfcbb77715f2c9556b28cc0bb75f929b/Helpers/ConversionHelper.cs#L60) doesn't seem to be utilized at all

**Comment by paolosalvatori** [comment]
Hi guys
any news on this issue?
Ciao
Paolo

**Comment by SeanFeldman** [comment]
@jonsb would you like to submit a PR? If not, I can do it.

**Comment by jonsb** [comment]
I'd be happy to submit a PR. But what about adding unit tests? I can add a unit test project and a couple of tests for my fix stating my assumptions. Ref issue #36, which is "done" - what does that mean?

**Comment by SeanFeldman** [comment]
#36 is closed. My bad.
