### ISSUE TITLE
Able to delete the topics from Service bus and which is not storing any logs in Azure.

### ISSUE THREAD

**Issue by Ankasalahari** [paolosalvatori/ServiceBusExplorer#357]
when we login into the service bus explorer by using connection string we can see the data which don't have the security and if anybody having that connection string those can delete the topics and create the topics . The locks that we are putting on the topics or subscriptions are not working when we perform any action those. Apart from this there is no logs in azure if we modify it from service bus explorer. I can see logs on service bus explorer upto that session only .

**Comment by ErikMogensen** [comment]
Unfortunately that is how it works when you use SAS to connect to Service Bus. However about a year ago the ability to authenticate using Azure AD credentials was added to Service Bus. There is a PR for adding that functionality to Service Bus Explorer, #394. Using Azure AD credentials I am pretty sure that there will be logs for such things you are describing.

Do you want to Service Bus Explorer logs to be persisted to disk?

**Comment by paolosalvatori** [comment]
Let me add that Service Bus Explorer needs a Shared Access Signature token with the manage claim, otherwise it cannot browse entities. In theory, you could also specify Shared Access Signature tokens for individual entities, but this is not supported by the tool.

Regarding the Azure AD support, we need to migrate the entire tool to the new client library which supports Azure AD authentication.

Regarding logs, I assume you mean Activity Logs. What kind of operation would you like to track? CRUD operations on entities such as topics and queues? In order to keep track of these operations, you need to configure the diagnostics settings for your Service Bus namespace and collect this data in a Log Analytics workspace. Let me know if this answers your question so I can proceed and close the issue.

**Comment by aaronumerouno** [comment]
Hi @paolosalvatori Not sure if its been implemented yet but yes please include additional logging for CRUD operations of Queues,relays and topics to the service bus explorer i.e specially as who has initiated it. If SAS was used to connect and we cannot determine who maybe the current used logged in to the pc is logged?

**Comment by aaronumerouno** [comment]
> Let me add that Service Bus Explorer needs a Shared Access Signature token with the manage claim, otherwise it cannot browse entities. In theory, you could also specify Shared Access Signature tokens for individual entities, but this is not supported by the tool.
> 
> Regarding the Azure AD support, we need to migrate the entire tool to the new client library which supports Azure AD authentication.
> 
> Regarding logs, I assume you mean Activity Logs. What kind of operation would you like to track? CRUD operations on entities such as topics and queues? In order to keep track of these operations, you need to configure the diagnostics settings for your Service Bus namespace and collect this data in a Log Analytics workspace. Let me know if this answers your question so I can proceed and close the issue.

@paolosalvatori - im not sure if im doing incorrectly but I tried the configuration of diagnostic settings of my Service Bus Namespace but CRUD ops done in Service Bus explorer doesnt get logged to log analytics.

**Comment by SeanFeldman** [comment]
@aaronumerouno, I would assume CRUD operations on entities in a namespace would be logged by the broker rather than SBE. Custom information, such WHO has initiated the operation will be tricky as it would rely on some information that doesn't necessarily always there or helpful. Would it be a machine name? Current user ID? What if the tool is used from a temporary VM? Would that user ID make any sense? Just asking these questions to see what is a good trade-off and where it makes sense.

**Comment by aaronumerouno** [comment]
> @aaronumerouno, I would assume CRUD operations on entities in a namespace would be logged by the broker rather than SBE. Custom information, such WHO has initiated the operation will be tricky as it would rely on some information that doesn't necessarily always there or helpful. Would it be a machine name? Current user ID? What if the tool is used from a temporary VM? Would that user ID make any sense? Just asking these questions to see what is a good trade-off and where it makes sense.

Hi @SeanFeldman - you are right, I edited my response to Paolo,  log analytics logs only show in the column Caller_S as ServiceBus Client. I gave it some thought on how to record WHO has done the change, how about a force log in to Azure portal before being able to use SBE? then use that user login session to send CRUD logs to the Service Bus Namespace activity log, just an idea.  I am assuming that people who use the SBE will already have login to portal and im assuming that the service bus sdk allows this.

**Comment by SeanFeldman** [comment]
Currently, SBE relies on a connection string to be able to use SB namespace(s). It doesn't use AAD authentication.

**Comment by paolosalvatori** [comment]
Hi @aaronumerouno Service Bus Explorer is just one of the many applications that can be used to interact with the messaging entities in a Service Bus namespace. The tool is not meant to log CRUD operations for a couple of reasons:

1. Logging CRUD operations can be achieved by configuring diagnostics settings on a Service Bus namespace to collect logs and metrics to a Log Analytics workspace. If the information collected is not enough, I suggest you submit an issue at https://github.com/Azure/azure-service-bus.
2. Service Bus Explorer could only log the operations done by the local instance, for sure not by other instances of the tool or using other mechanisms like ARM templates, REST API, Azure portal, etc.
3. As mentioned by Sean, currently SBE relies on connection strings to connect a Service Bus namespace. This may change in the future, but for the time being this is the status quo. :)
