### ISSUE TITLE
Verification when delete of Queue

### ISSUE THREAD

**Issue by Jemob** [paolosalvatori/ServiceBusExplorer#377]
Hi!
It is a very good tool, but i have a problem that it is very easy to delete a queue with no verification question. Is it possible for me to disable the delete options on queue level? or is it possible to get an verification, do you really want to delete queue as it is when you delete messages?

#feature

/Jennie

**Comment by SeanFeldman** [comment]
Verification (confirmation) is already in place
![image](https://user-images.githubusercontent.com/1309622/64970341-d09f3480-d862-11e9-8679-7f4b1f4adef6.png)

**Comment by Jemob** [comment]
Oh, in wich version did this come? 
I run the 4.1.112, is this in an later version?

**Comment by SeanFeldman** [comment]
Been there a while...

**Comment by ErikMogensen** [comment]
@jemob, unfortunately older versions of SBE always report their version as the latest released version since they get the version number using a REST call to Github. If your SBE states its version in the title of the main window it is an old version. The title should only say Service Bus Explorer, like the figure below:
![image](https://user-images.githubusercontent.com/9644248/65060261-dcc8e600-d977-11e9-9d8d-8c76f496bc65.png)

**Comment by ErikMogensen** [comment]
However I think the default button should be No and you should have to type the name of the namespace when deleting all queues.

**Comment by Jemob** [comment]
> @Jemob, unfortunately older versions of SBE always report their version as the latest released version since they get the version number using a REST call to Github. If your SBE states its version in the title of the main window it is an old version. The title should only say Service Bus Explorer, like the figure below:
> ![image](https://user-images.githubusercontent.com/9644248/65060261-dcc8e600-d977-11e9-9d8d-8c76f496bc65.png)

Thank you so much for the reply. I will try to download a new version then. :)
It is like you wrote an version number in the title.
