### ISSUE TITLE
Multiple send messages windows incorrectly share message properties

### ISSUE THREAD

**Issue by mrtaunus** [paolosalvatori/ServiceBusExplorer#383]
We have an ASB topic to which we send different types of messages. To test this locally, we usually open two "Send Messages" windows in Azure Service Bus Explorer so that we do not need to start from scratch every time we want to change the message type to send.

Otherwise this works just fine, but the Message Properties window seems to be interlinked in these separate "Send Messages" windows. I.e. updating a custom property in one window, the same property is also updated in the other window. This causes quite some problems as the message properties are then used in the filtering of the subscriptions, and we need to remember to correct these for each message we send from different windows.

The problem goes worse if we try to add new properties. This change is not reflected on the other window, but the indexes go haywire and we start to get index reference errors in the main window.

**Comment by SeanFeldman** [comment]
Sounds like an issue with concurrency on UI.
I'd say as a workaround open two SBExplorer instances.

**Comment by SeanFeldman** [comment]
@paolosalvatori have you ever encountered a use such as described by @mrtaunus ?

**Comment by mrtaunus** [comment]
> Sounds like an issue with concurrency on UI.
> I'd say as a workaround open two SBExplorer instances.

This indeed circumvents the problem, thank you Sean. It's not ideal, but I can live with that.

**Comment by paolosalvatori** [comment]
@mrtaunus @SeanFeldman this behavior is by default and I don't see viable \ valid alternative. The tool reads properties from the Properties.xml file located in the folder containing ServiceBusExplorer.exe any time you open a Send Messages form and writes properties back to the file any time you update and then close the form. 

```xml
<?xml version="1.0" encoding="us-ascii"?>
<Properties xmlns="http://schemas.microsoft.com/servicebusexplorer">
  <Property Key="country" Type="String" Value="Italy" />
  <Property Key="city" Type="String" Value="Milan" />
  <Property Key="sender" Type="String" Value="ServiceBusExplorer" />
</Properties>
```
In order to implement the ability to use a different set of properties, we should:

- provide the ability from the UI to read \ write properties from an alternative file other than Properties.xml
- in this case, we may extend the business logic to allow reading properties also from a JSON file with the same format of the Properties.xml

```json
{
    "properties": [
        {
            "name": "country",
            "value": "Italy"
        },
        {
            "name": "city",
            "value": "Milan"
        },
        {
            "name": "sender",
            "value": "ServiceBusExplorer"
        }
    ]
}
```
