### ISSUE TITLE
Confusing UI to delete messages, queue and topics

### ISSUE THREAD

**Issue by divyaksh-shukla** [paolosalvatori/ServiceBusExplorer#399]
The UI is confusing to use to delete messages, queues or topics and there is no confirmation dialog while deleting the same

**Comment by SeanFeldman** [comment]
Hi @divyaksh-shukla,

Thank you for the feedback. I think there are several questions/suggestions in a single issue here, so I'll try to see if can answer and split those into stand-alone issues (issues are better handled when scoped to a single problem).

> The UI is confusing to use to delete  queues or topics 

The right click menu on the entity or a <kbd>Del</kbd> key on the keyboard are very standard in Windows UX. Perhaps you want to raise a separate issue to describe how that could be done better? If you're running an older version of the tool, you might not have it. Updating would help.

![image](https://user-images.githubusercontent.com/1309622/71024979-5a110d80-20c3-11ea-9608-b5d31345f145.png)

> there is no confirmation dialog while deleting the same

What version are you using? There is a confirmation dialog box when an entity is about to be deleted.

![image](https://user-images.githubusercontent.com/1309622/71024879-259d5180-20c3-11ea-85a5-14c6f3a14e3a.png)

> The UI is confusing to use to delete messages

Service Bus does not have a "purge" functionality. Messages must be received. That's why to delete messages you have to receive those messages with `ReceiveAndDelete` mode.

In the recent versions <kbd>Purge</kbd> was added. I have a strong feeling you need to get the [latest version](https://github.com/paolosalvatori/ServiceBusExplorer/releases).

![image](https://user-images.githubusercontent.com/1309622/71025243-dc99cd00-20c3-11ea-9fc4-5185459930ac.png)

Should you still have issues or feedback, please consider raising specific issues to focus on one item at a time. Will leave the issue open to give you an opportunity to confirm the questions are answered or not. Thanks.

**Comment by divyaksh-shukla** [comment]
Thank you the prompt reply
Looks like my service bus explorer window was sized in such a way that the delete button on the lower right was on the center of the screen where it spawns the confirmation dialog box, and surprisingly my mouse kept miss-clicking all the time I was trying to click the delete button and clicked twice causing me to delete the queue and topic without even having a look at the confirmation dialog.  It was really stupid of me to not resize the service bus explorer window before posting this issue.
