### ISSUE TITLE
Sas token access to Service bus

### ISSUE THREAD

**Issue by riteshvaryani** [paolosalvatori/ServiceBusExplorer#50]
Hi,

We are generating SAS tokens for rules defined at entity levels for topics and queues. The Service Bus Explorer takes a connection string, a SAS connection string but not an expiring SAS token to allow a connection at an entity level. Are there any other ways to connect using a SAS token to service bus.

**Comment by paolosalvatori** [comment]
Hi 
The Service Bus Explorer only supports connection strings at the namespace level with the Manage right\claim. I should modify the tool to allow this option. I never did that because, it would be costly and the tool is mean to be used by a system administrator. The only exception is the listener for IoT Hubs which accepts a connection string with only the Listen claim.
Ciao
Paolo

**Comment by niteenb4u** [comment]
Even my question is same as @riteshvaryani , I have given limited to one of the service bus topic to my client, now he wants to see the messages in the topic through service bus explorer, but it shows empty screen. 
How can I see the topic message? any other tool is available?

**Comment by paolosalvatori** [comment]
Hi @niteenb4u, as I said above, the tool just supports namespace-level connection string. The tool should be extended to support entity-level connection strings. I'm not aware of any free tool that allows to see the content of an existing queue or topic-subscription given an entity-level connection string with at least the receive claim. The tool can be easily extended to implement this feature, I just don't have the necessary bandwidth in this period. Sorry about that.
