### ISSUE TITLE
Filter queues and topics by name

### ISSUE THREAD

**Issue by mrpmorris** [paolosalvatori/ServiceBusExplorer#526]
I have about 100 queues/topics in a single ServiceBus and it takes a while to navigate.

A text box above the queues/topics tree for filtering items would be great.

If I were to submit a PR would this be something you'd consider including?

**Comment by ErikMogensen** [comment]
PRs are almost always most welcome, but have you seen the existing filter capability?

![image](https://user-images.githubusercontent.com/9644248/112665953-ea5c0780-8e5b-11eb-9046-1721eeb83e3e.png)

**Comment by mrpmorris** [comment]
No,  I was unable to find the option. 

Thanks!

**Comment by mrpmorris** [comment]
I see, it filters on the server.

That's a shame, I wanted more than StartsWith because all of my queues/topics end with different suffixes that I want to filter by :(

**Comment by ErikMogensen** [comment]
There was an issue about the same functionality that you are wishing for, #452.

@mrpmorris, I think it would be great if you created a PR for that. I am sure @SeanFeldman and @paolosalvatori agrees. I like your idea of having a textbox above where the filter would be visible. 

Also, as far as I know, the Startswith functionality does not exist in the latest SDK for Service Bus so if you build something that does not rely on StartsWith it would make it easier to migrate it to the latest SDK in the future.

**Comment by mrpmorris** [comment]
I don't think the service bus api supports any kind of "contains"

**Comment by paolosalvatori** [comment]
@mrpmorris when I created the Service Bus Explorer years ago I provided the ability to specify filters in the Connect form and context menus. I used and implemented the filters that were available at that time. It looks that nothing has changed since then at least in the old client SDK Microsoft.ServiceBus.dll. For example, the NamespaceManager.GetQueues(String) method
retrieves an enumerable collection of all queues in the service namespace with the specified filter. You can filter by a combination of entity name (including starts with), entity length (Gt or Lt), created, updated, and accessed time (Gt or Lt). Hence, no support for the contains predicate.
The ManagementClient.GetQueuesAsync method in the new Microsoft.Azure.ServiceBus library doesn't even support the possibility to pass a string which contains a filter.-

**Comment by mrpmorris** [comment]
Yeah, I saw that :(

Seeing as the whole list is retrieved when connecting we don't actually save anything by filtering on the server.  So maybe the client could do the filtering?

**Comment by ErikMogensen** [comment]
I think it would be great if the client did the filtering. Since it is a bit confusing with three SDKs for Service Bus here is a [link to what I consider the preferred method](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.getqueuesasync?view=azure-dotnet#Azure_Messaging_ServiceBus_Administration_ServiceBusAdministrationClient_GetQueuesAsync_System_Threading_CancellationToken_) for getting queues in the latest SDK. 

It might be quite a task to replace the existing filtering with something based on that method, but it would be highly appreciated.

**Comment by paolosalvatori** [comment]
@ErikMogensen yes we can certainly implement filtering on the client-side, but there are customers that have namespaces with hundreds not say thousands of queues and topics and in that case, it would be useful to have the filtering capability on the server-side to avoid downloading a ton of entities from the cloud 😢

**Comment by ErikMogensen** [comment]
@paolosalvatori, I think most of the time is spent retrieving the runtime information for the queues, so client-side would be almost as effective. Also, if we don't accept client-side filtering we won't be able to migrate to the latest Service Bus SDK unless the Service Bus PG implements server-side filtering.

**Comment by mrpmorris** [comment]
@paolosalvatori As soon as you connect, the client downloads all of the queues + topics anyway so that time is already spent.

Filtering on that list in memory would be quicker than asking the server to filter the list in memory and then return it over the network.

Or am I missing something obvious?

**Comment by paolosalvatori** [comment]
@mrpmorris well, the client does not download queues and topics data unless you explicitly call the GetQueues and GetTopics methods 😃 Anyway, if you guys have the bandwidth to implement client-side filtering, go with that, I'm fully supportive 😄

**Comment by mrpmorris** [comment]
I had a crack at it, but the presentation and operational logic is mixed together and I found it too much work to understand & separate them.

**Comment by ErikMogensen** [comment]
Thanks for trying @mrpmorris!

**Comment by mrpmorris** [comment]
How would you feel about application code being migrated to something like Fluxor so it can be completely separated from the code needed to present the data in the UI?

**Comment by ErikMogensen** [comment]
The top of the search in https://github.com/mrpmorris/Fluxor. Are you the author of it? 

Could you describe the pros and cons of migrating to it. Consider that Service Bus Explorer contains about 50.000 lines of code (depends on how you count it) in Windows Forms and there are no dedicated developers. Everything is driven by voluntary effort, sometimes financed by organizations wanting a certain feature.

**Comment by mrpmorris** [comment]
It's a clean way to separate the operational logic out of the code you need to control UI (disabling buttons, handling clicks etc).

Implementing the client-side filter would have been easy. You'd fire a FilterChangedAction(value of the input) every time the input changed - and then a single function would only include nodes that matched the filter.

It wouldn't be a small amount of work. But that's not because the Flux pattern is a lot of work, but because you have so much code and it's mixed together.

**Comment by paolosalvatori** [comment]
@mrpmorris I started the project as a sample 10 years ago when the Service Bus was actually launched. Then I migrated the project to GitHub in September 2014. Since then I've been the primary contributor, but now most of the changes come from the community. There's no direct involvement of the product group in the project, despite I'm a Microsoft employee, and I'm too busy to embark on a full rewrite of the tool. So even I agree with your idea, I doubt that we have the bandwidth for a migration.
