### ISSUE TITLE
"Delete Lock" on Queue or namespace does not prevent queue from deleting. 

### ISSUE THREAD

**Issue by ab-shah** [paolosalvatori/ServiceBusExplorer#532]
With lock on namespace or queue itself, service bus queue cannot be deleted. When delete from Portal it gives message like following 

**_Failed deleting Service Bus queue [queuname] with error code: ScopeLocked and with message: The scope '/subscriptions/[subscriptionid]/resourceGroups/[resourcegroupname]/providers/Microsoft.ServiceBus/namespaces/[namespace]/queues/[queuname]' cannot perform delete operation because following scope(s) are locked: 'subscriptions/[subscriptionid]/resourceGroups/[resourcegroupname]/providers/Microsoft.ServiceBus/namespaces/[namespace]'. Please remove the lock and try again.._**

However locks are ignored in ServiceBusExplorer.

**Comment by ErikMogensen** [comment]
Yes, that is unfortunate but that is due to the connection to the queue is done using SAS which bypasses ARM. ARM handles auditing, permission check using RBAC (the permissions you set on Azure artifacts, resource groups and subscriptions) and the locks. 

When Service Bus Explorer was created it wasn't possible to connect to queues using ARM - I don't even think it existed outside of Microsoft. Since about two years ago it is possible and we have that on the roadmap. However, since this project is only driven by voluntary efforts it is impossible to say when that will be implemented. 

There is some discussion about ARM in #507.
