### ISSUE TITLE
Enforce Message Ordering setting

### ISSUE THREAD

**Issue by lindgrend** [paolosalvatori/ServiceBusExplorer#538]
We are trying to manually change the Max delivery count via both powershell and the C# sdk and this is working, however when we open the queue in the ServiceBusExplorer we see that this has also added the Enforce Message Ordering property to true. 
![image](https://user-images.githubusercontent.com/8226441/117292553-a43d8f00-ae70-11eb-8bce-f0d9e84f6d66.png)

I would not expect this to happen automatically since I can't seem to find a way to set this property using the above methods or documentation. I also can't find the property in the queue section of the Azure portal.  Am I missing something or is this something that isn't used anymore/a visual bug

**Comment by ErikMogensen** [comment]
A long time one of the Service Bus architects told me that the _Enforce Message Ordering_ property didn't matter for queues. It is probably still true because I see that in the latest Service Bus SDK [this property has been removed](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.createqueueoptions?view=azure-dotnet),

In the old Service Bus SDK, which is used in this part of Service Bus Explorer, the [QueueDescription.SupportOrdering](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queuedescription.supportordering?view=azure-dotnet#Microsoft_ServiceBus_Messaging_QueueDescription_SupportOrdering) is used to handle this. 

We are slowly migrating from the old Service Bus SDK to the latest so when that is done for this part this property won't be visible anymore.

If you really want to know if this property matters, create a case with Microsoft. In that case... please put the outcome of the case in this thread.

**Comment by lindgrend** [comment]
Thanks for the fast reply, I will ask for more information from Microsoft and update this post with the result.
