### ISSUE TITLE
Azure resource locks don't prevent topic/subscription deletion

### ISSUE THREAD

**Issue by rgourleypython** [paolosalvatori/ServiceBusExplorer#579]
One of our subscriptions was accidentally deleted using Service Bus Explorer even though we have a delete lock on the Service Bus resource. We opened a case with Microsoft and received the following response:

![image](https://user-images.githubusercontent.com/78980727/125983945-009ad7e2-74e9-435f-bf0f-905d5aabb779.png)

Can Service Bus Explorer be updated to do deletions through the ARM layer so the delete lock is respected? Or can Service Bus Explorer at least check for a delete lock before allowing deletions?

Thank you,
Ryan

**Comment by ErikMogensen** [comment]
We are aiming for adding ARM layer support but since development is done on a voluntary basis it hasn't happened yet. Currently ServiceBusExplorer is using two different Service Bus SDKs which makes this task more difficult too.

Regarding respecting the resource lock it is impossible since there is no way to see that lock when only having a SAS style connection string.

**Comment by ErikMogensen** [comment]
Adding that RBAC support, which is the same as ARM layer support, is mentioned in https://github.com/paolosalvatori/ServiceBusExplorer/projects/1#card-9365395.
