### ISSUE TITLE
Better UI for Message Custom Properties pane

### ISSUE THREAD

**Issue by aeslinger0** [paolosalvatori/ServiceBusExplorer#584]
Could you make it so we can see the entire Value of the "Message Custom Properties" pane for a Queue? Right now if the text wraps, there's no way to see the rest of the text. Also can you make it so we can copy/paste from it? The text is not currently selectable or copyable.

I'm guess the same could be said of the "Message System Properties" pane as well.

Thanks.

**Comment by ErikMogensen** [comment]
@aeslinger0, that sounds very good. However, since the development is done by the community your best bet of getting this improvement is to do it yourself. We'd be happy to get a PR for this.

**Comment by jcoeltjen** [comment]
I believe this issue is outdated as the current version (at least 5.0.4) has already a fix for this implemented.
You can easily copy the values from the new UI via double clicking into the text field.

![image](https://user-images.githubusercontent.com/7881529/136058253-097248f0-a05d-4f04-b0bc-05e6ba644936.png)

**Comment by ErikMogensen** [comment]
> I believe this issue is outdated as the current version (at least 5.0.4) has already a fix for this implemented. You can easily copy the values from the new UI via double clicking into the text field.
 
Great. Let's close this before the bot.
