### ISSUE TITLE
Release 5.0.5 zip only contains VERIFICATION.txt

### ISSUE THREAD

**Issue by kylejuliandev** [paolosalvatori/ServiceBusExplorer#629]
Hi,

I downloaded the latest release [5.0.5](https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/5.0.5) and noticed that the zip only contained a file VERIFICATION.txt (see below) and appears to be missing the executable.

![explorer_O9r4Meu7C0](https://user-images.githubusercontent.com/38759683/162011015-fd0cbb07-430b-4355-90b6-8765e961f9e0.png)

Let me know if you need any other details,

Kind Regards,

Kyle

**Comment by SeanFeldman** [comment]
@kylejuliandev, there's been some change made that has broke the packaging.
![image](https://user-images.githubusercontent.com/1309622/162017680-4961f323-9c27-4b31-b1b7-56ac581a1745.png)

The application is packaged as a NuGet application and the files are in the .nupkg file, under the `tools\net462` folder 
![image](https://user-images.githubusercontent.com/1309622/162017947-2949ef46-a5fe-4548-9481-1e205c62d99b.png)

As a workaround, you could extract it from there until `.zip` file is fixed in 5.0.6

**Comment by 0xced** [comment]
Also, the path inside the NuGet package has changed from `tools` to `tools\net462` between version 5.0.4 and 5.0.5.

Not a big deal, but I had to manually adapt the [scoop manifest](https://github.com/ScoopInstaller/Extras/pull/8273) which would have otherwise automatically updated without issues.

**Comment by SeanFeldman** [comment]
I don't have the capacity to fix it right away 🙁 If anyone wants to land a hand that'd be very appreciated 🙏
