### ISSUE TITLE
[Feature Request] Multiple Connections

### ISSUE THREAD

**Issue by adamrybak** [paolosalvatori/ServiceBusExplorer#661]
I work with multiple service buses and would like to be able to have multiple connections open at the same time.

I'd imagine it would look something like this:
![image](https://user-images.githubusercontent.com/32214327/178407002-757b41ba-61db-4c26-b150-c7a23be866a4.png)

**Comment by SeanFeldman** [comment]
@adamrybak, not possible today w/o opening multiple windows. Could you describe what do you do with the two namespaces at the same time?

**Comment by adamrybak** [comment]
Hi @SeanFeldman, there is no particular cross namespace function that I am performing however it would be nice to be able to refresh all the queues at once so I may see top down where there may be concerns with the message counts.

Perhaps even on top of this, being able to open a whole group of namespaces at once would be nice too.

For the interim, multiple windows works however inconvenient.

**Comment by SeanFeldman** [comment]
I think the first part of your request would be somewhat covered by #188.

Side note: personally, I'd not refresh multiple namespaces with multiple entities. If you have many of those, I'd think about a solution where you get notified about important things, and alerted, rather than monitoring counts yourself.
