### ISSUE TITLE
Cannot save connections

### ISSUE THREAD

**Issue by jamie-shark** [paolosalvatori/ServiceBusExplorer#666]
Version 5.0.7

I am trying to save a connection.  I have re-installed and have the same issue.

I am on a fresh install from chocolatey
I go to File > Connect
I select "Enter a connection string" and paste in my connection string
I click Save, and then Ok with the Key unchanged
The connection is not saved, and I get the following Logs:

<14:58:03> The file C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\ServiceBusExplorer.exe.Config is used for the configuration settings.
<14:58:22> Exception: An error occurred loading a configuration file: Access to the path 'C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\nfnicp4j.tmp' is denied. (C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\ServiceBusExplorer.exe.Config)
<14:58:22> InnerException: Access to the path 'C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\nfnicp4j.tmp' is denied.

**Comment by ErikMogensen** [comment]
This looks like it is due to the path where it tries to save the configuration file requires elevated access. There are a couple of solutions for this but the best one is probably just to change where it stores connection strings. You do that in View | Options 
![image](https://user-images.githubusercontent.com/9644248/186252154-bc0229dd-76d3-4179-af21-9fe6d52bf97a.png)
Select _User Configuration File_, click _Save_ and _OK_.

**Comment by tonesoutherland** [comment]
Alternately, you can run the program as administrator and it should allow you to save to the choco folder. This is how I get around this issue.
