### ISSUE TITLE
5.0.15 - Cannot retrieve messages from a queue

### ISSUE THREAD

**Issue by brendonious8** [paolosalvatori/ServiceBusExplorer#710]
Hey all,

Having issues peeking messages from certain queues. Have tried deleting/recreating the queue and running Service Bus Explorer in admin mode.

The Service Bus Explorer has a spinning circle then sends back this error message.

<10:15:50> The timeout  of [20] seconds has expired and no message was retrieved from the queue [sbq-legacyservice-newtonproductprocessing].

Can reliably peek deadletter messages from the queues and some other queues can return messages.

<10:17:05> [0] messages peeked from the queue [sbq-salesforceleadupsert].

Any ideas?

**Comment by ErikMogensen** [comment]
I'd say that is due to a large message or the backend is feeling ill. Please try one or more of the following and let us know the results:
* Increase the Receive timeout to 120 seconds:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/9644248/211661901-3641b2a3-44ad-451c-9b58-f1e844cb1810.png">
* You wrote that you had recreated a queue but you can try to change a non-important queue property, such as "Enable batched operations" then Update and then change it back again and then Update again. That will cause the queue/partition to be handled by a different server
<img width="224" alt="image" src="https://user-images.githubusercontent.com/9644248/211662204-4e4db005-487e-4d78-bcfb-2fea5fe44091.png">

* Test peeking using the Portal Service Bus Explorer to see if there is something wrong with the queue or the Desktop SBE.


Is this on the Premium tier?

**Comment by ErikMogensen** [comment]
Closing due to no reply.
