### ISSUE TITLE
Cannot connect to Microsoft Service Bus with v3.4.23

### ISSUE THREAD

**Issue by fergusontom** [paolosalvatori/ServiceBusExplorer#76]
I cannot connect to an on premise Windows Service Bus instance with version 3.4.23 (or 3.4.18). I reverted to v2.1 and it works fine with the same connection string.

The connection string looks a bit like this:
`Endpoint=sb://xxx/abc,sb://yyy/abc,sb://zzz/abc;StsEndpoint=https://xxx:9355/abc,https://yyy:9355/abc,https://zzz:9355/abc;RuntimePort=9354;ManagementPort=9355;WindowsUsername=user;WindowsDomain=domain;WindowsPassword=password`
[Redacted]

Note that I am impersonating another user when connecting.

The service bus instances have self signed certificates, but I have trusted all of them on my local machine.

As I say, it works fine in 2.1, but not in 3.4+ Could this be because the impersonation does not work in these versions?

**Comment by paolosalvatori** [comment]
Hi Ferguson
any version of the Service Bus Explorer tool that is higher than 2.1.3 does not work with the on-premises version of the Service Bus by definition. This is not due to the tool, but to the Microsoft.ServiceBus.dll used by the tool as the latter is not compatible with the on-premises version of the Service Bus. This is clearly mentioned in the main page here on GitHub. :)
Ciao
Paolo
