### ISSUE TITLE
UI doesn't scale correctly

### ISSUE THREAD

**Issue by Splaxi** [paolosalvatori/ServiceBusExplorer#784]
Using the latest release - on Windows 11, Microsoft Surface, the UI doesn't scale:

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/8750181/b919d061-53bc-43ac-89d4-188336e51055)

It seems that the right anchor isn't is configured correctly. The scroll bar doesn't show if I minimize to a non-full screen mode.

Is this by design?

**Comment by maf-soft** [comment]
Same here, and after "Set Default Layout", the Log area is completely out of the window and not reachable anymore.

**Comment by ErikMogensen** [comment]
No, that's not the way it is supposed to look.

**Comment by ErikMogensen** [comment]
@Splaxi, @maf-soft I am unable to reproduce this.

1. Are you using v6.0.0?
2. Is it the same in 5.0.18?
3. @splaxi, what is the Scale setting? It is under Settings | System > Display
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/3d76fab3-8472-4680-9df1-8d6f9bf32865)
4. Anything else you can think of that would cause this bahavior?

**Comment by maf-soft** [comment]
Yes, I used choco to update from 5.0.18 (where it looked ok) to 6.0.0. It runs on a VM with WindowsServer 2022-datacenter-azure-edition, the RDP client is Win11.

**Comment by maf-soft** [comment]
Ah the client has multiple screens in my case. If I move the RDP window to the other screen, which has a scaling of 250%, the wrong proportions look exactly the same, just everything 250% larger.

**Comment by Splaxi** [comment]
Single monitor, zip file download directly from GitHub.

Not around my machine at the moment.

No issues in v5 - version was not the latest v5 though....

**Comment by Splaxi** [comment]
Okay.

Microsoft Surface Laptop 4, running directly on battery. No cables connected.

With scale set to 100% - it looks like this:

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/8750181/11a0acc1-78d0-4bd7-90b5-e378cfce8a0b)
- All edges and boxes looks like expected

Settings are like this: 
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/8750181/9485c97d-3b1e-421e-b1e0-3ee94cbb597c)

Anything other than 100%, eg. 125/150% - yields the following result:

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/8750181/5441d70f-b80c-4884-9411-ec114c751953)
- All edges on the right hand side, and boxes (log) are overflowing to right hand side.

Settings are like this:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/8750181/5f79d3c4-ed50-41ed-a404-3615d2f7fdd7)

Running any scale beyond 100%, with custom resolution settings (non-recommend), yields the same result. The edges on the right hand side and boxes doesn't look as it should.

**Comment by jamesmanning** [comment]
Just another data point - 250% scale, win11, screen resolution 3840x2400 - 5.0.18 looked fine, 6.0.0 results in 4.5 of the subscription modification buttons being cut off, no matter how wide I make the window. In my small amount of previous winforms experience, I usually had this issue when I needed to anchor things to the right side instead but I'm not sure what's the actual issue here.

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/166409818/e2c58bc9-6762-48ac-9427-70b53577de13)

**Comment by ErikMogensen** [comment]
It looks like someone was doing GUI changes using VS in DPI aware mode. 

I believe I fixed it. If you are able to build it you can clone https://github.com/ErikMogensen/ServiceBusExplorer/tree/FixUiScaling and try that branch. 

Otherwise you'll have to wait until it is released.

**Comment by Splaxi** [comment]
I can confirm the branch does in fact fix the issue.

It loads my current saved connections and scales as expected, regardless of what I throw at it.

Thanks for taking the time to look into it - Now the waiting begins 🤞

**Comment by ErikMogensen** [comment]
6.0.1 is now released, https://github.com/paolosalvatori/ServiceBusExplorer/releases/tag/6.0.1. It will take some time until it is available on Chocolatey.

Thanks for providing information and testing!

**Comment by Splaxi** [comment]
Thanks for the fast assistance.

I believe that you might need to bump the version of the exe file - to have the "New Version is available" notification to work properly 😉

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/8750181/cf97edae-0f7a-4f12-ad56-c1ba3ed60a92)

**Comment by ErikMogensen** [comment]
Thanks for the warning. Version stamping is done automatically - if it works as it should... 

In this case I think that you installed it using choco or scoop and got an old version. It seems that chocolatey takes a lot of time to update. The zip file on GitHub for version 6.0.1 contains an exe with a proper version number.

**Comment by jamesmanning** [comment]
@ErikMogensen FWIW, in noticing 6.0.1 hasn't shown up in winget yet, it appears that as it stands, someone runs the komac tool to submit a new version, as @Ancient77 did last week

https://github.com/microsoft/winget-pkgs/pull/159876

It also seems like there's an github action available that would help automate this to prevent people from having to take this manual step when new versions are published - is this (or some similar automation for publishing to winget) possibly an option for ServiceBusExplorer for future versions, please? 🙏 

https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-

It seems like this isn't needed for choco/scoop since those seem to have picked up 6.0.1 already. I'm a little surprised winget doesn't have some kind of automation on its own to pick up new releases from a github project, admittedly. Or maybe it does and there's something off with it? Not sure.

https://community.chocolatey.org/packages/ServiceBusExplorer
https://github.com/ScoopInstaller/Extras/blob/master/bucket/servicebusexplorer.json
