### ISSUE TITLE
Not able to connect to Service Bus after upgrading to the latest version

### ISSUE THREAD

**Issue by viveknuna** [paolosalvatori/ServiceBusExplorer#810]
I am getting the below error while connecting to a service bus using the connection string. It was working fine before upgrading to the latest version. I mainly want to connect to the topics.

> <13:03:06> The file C:\Users\Vivek.Nuna\AppData\Roaming\Service Bus Explorer\UserSettings.config is used for the configuration settings.

![image](https://github.com/user-attachments/assets/c905f78a-9090-4855-8f6e-2920053f7e06)

> <13:03:55> The application is now connected to the sb://sb-eu-ci-prem-defaul-0x1.servicebus.windows.net/ service bus namespace.
> <13:03:55> MessagingFactory successfully created.
> <13:04:08> Failed to retrieve Service Bus queues. Exception: System.TimeoutException: The operation has timed out.
> 
>               at ServiceBusExplorer.ServiceBusHelper.GetQueues(String filter, Int32 timeoutInSeconds) in D:\a\ServiceBusExplorer\ServiceBusExplorer\src\Common\Helpers\ServiceBusHelper.cs:line 1594
> 
>               at ServiceBusExplorer.Forms.MainForm.<ShowEntities>d__361.MoveNext() in D:\a\ServiceBusExplorer\ServiceBusExplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4615
> <13:04:08> Failed to retrieve Service Bus topics. Exception: System.TimeoutException: The operation has timed out.
> 
>               at ServiceBusExplorer.ServiceBusHelper.GetTopics(String filter, Int32 timeoutInSeconds) in D:\a\ServiceBusExplorer\ServiceBusExplorer\src\Common\Helpers\ServiceBusHelper.cs:line 1749
> 
>               at ServiceBusExplorer.Forms.MainForm.<ShowEntities>d__361.MoveNext() in D:\a\ServiceBusExplorer\ServiceBusExplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4656

![image](https://github.com/user-attachments/assets/f3474a17-e1bc-4535-b1c7-092ad28832a9)

I have upgraded using chocolaty.

https://github.com/paolosalvatori/ServiceBusExplorer?tab=readme-ov-file#upgrading

@SeanFeldman

**Comment by viveknuna** [comment]
@paolosalvatori @SeanFeldman @ErikMogensen Could you please help on this?

**Comment by SeanFeldman** [comment]
I'm on 6.0.3 and see no issues. Have you tried a different environment & ASB namespace?

**Comment by viveknuna** [comment]
Yes, I have tried different environments and ASB namespaces. It was working fine before upgrading.

**Comment by SeanFeldman** [comment]
I cannot troubleshoot someone else's environment, @viveknuna. 

You can try downgrading to the previous version and verifying it's working. If it doesn't see the differences. Try installing a brand new copy in a clean setup and see if that's working for you.

If the build was broken, you'd see many voicing the problem. I'm not saying there's not a chance something is off, but historically, it's usually a local issue rather than the build itself.

**Comment by viveknuna** [comment]
It wasn't solved by reinstalling the latest version, But by lowering down to 5.0.18. May be someone may investigate the root cause.

**Comment by SeanFeldman** [comment]
I'm not entirely sure what's causing it, @viveknuna. If there were multiple reports of the same problem, we'd try to help troubleshoot the root cause. But this was the only raised concern. If you have the cycles to look for what could cause the issue on your end between 5.0.18 and 6.0.3, please re-open the issue and share your findings.

Sorry, I don't have a better option now - the reality of a FOSS project.

**Comment by ErikMogensen** [comment]
@viveknuna , have you compared the servicebusexplorer.exe.config file in the release to the one you have? There are some references to assemblies in it that must match the version of service bus explorer that is used.  

Another thing that may cause trouble is if you have Microsoft.Service.dll in your GAC. Then it will interfere with Service Bus Explorer. It is possible that there may be another assembly that is in the GAC that interferes.
